// components/SEO.tsx — Safe Harbor
// Centralised metadata generator for all pages.
// Call generatePageMetadata() from generateMetadata() in each page.tsx.
// Structured data schemas: LocalBusinessSchema + PersonSchema.

import type { Metadata } from 'next'
import type { Locale } from '@/lib/utils'

export type PageName = 'home' | 'about' | 'services' | 'faq' | 'contact'

// ─────────────────────────────────────────────
// Base site URL — set NEXT_PUBLIC_SITE_URL in Vercel env vars before launch
// ─────────────────────────────────────────────
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://sofia-tarasov.com'

// ─────────────────────────────────────────────
// OG image paths — generated by opengraph-image.tsx in each route folder
// ─────────────────────────────────────────────
function ogImageUrl(locale: Locale, page: PageName): string {
  const path = page === 'home' ? `/${locale}` : `/${locale}/${page}`
  return `${SITE_URL}${path}/opengraph-image`
}

// ─────────────────────────────────────────────
// generatePageMetadata
// Drop-in replacement for per-page generateMetadata() boilerplate
// ─────────────────────────────────────────────
export async function generatePageMetadata(
  locale: Locale,
  page: PageName,
): Promise<Metadata> {
  const content = await import(`@/content/${locale}/${page}.json`)
  const { title, description } = content.default.meta

  const pagePath = page === 'home' ? '' : page
  const canonicalUrl = `${SITE_URL}/${locale}/${pagePath}`

  return {
    title,
    description,
    alternates: {
      canonical: canonicalUrl,
      languages: {
        he: `${SITE_URL}/he/${pagePath}`,
        ru: `${SITE_URL}/ru/${pagePath}`,
      },
    },
    openGraph: {
      title,
      description,
      url: canonicalUrl,
      locale: locale === 'he' ? 'he_IL' : 'ru_RU',
      images: [
        {
          url: ogImageUrl(locale, page),
          width: 1200,
          height: 630,
          alt: title,
        },
      ],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImageUrl(locale, page)],
    },
  }
}

// ─────────────────────────────────────────────
// LocalBusiness schema — homepage and contact page
// ─────────────────────────────────────────────
export function LocalBusinessSchema() {
  const schema = {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    name: 'Sofia Tarasov Psychotherapy',
    url: SITE_URL,
    image: `${SITE_URL}/images/sofia-hero.jpg`,
    priceRange: '$$',
    areaServed: 'Israel',
    availableLanguage: ['Hebrew', 'Russian'],
    '@id': SITE_URL,
    address: {
      '@type': 'PostalAddress',
      addressLocality: 'Rishon LeZion',
      addressCountry: 'IL',
    },
    telephone: '+972523777865',
  }

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  )
}

// ─────────────────────────────────────────────
// Person schema — About page
// ─────────────────────────────────────────────
export function PersonSchema() {
  const schema = {
    '@context': 'https://schema.org',
    '@type': 'Person',
    name: 'Sofia Tarasov',
    jobTitle: 'Psychotherapist',
    url: `${SITE_URL}/he/about`,
    image: `${SITE_URL}/images/sofia-hero.jpg`,
    knowsLanguage: ['he', 'ru'],
    worksFor: {
      '@type': 'LocalBusiness',
      name: 'Sofia Tarasov Psychotherapy',
      '@id': SITE_URL,
    },
  }

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
    />
  )
}
